import { type NextPage } from "next";
import Head from "next/head";
import RootLayout from "../components/layouts/RootLayout";
import Dashboard from "../components/main/Dashboard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Software House</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <RootLayout>
        <Dashboard />
      </RootLayout>
    </>
  );
};

export default Home;
